In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5]

5

In [6]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [7]:
benimDizim[3:8] = -5

In [8]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [10]:
baskaDizi = np.arange(0,24)

In [11]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
slicingDizisi = baskaDizi[4:9]

In [20]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [21]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
slicingDizisi[:] = 700

In [25]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [26]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [27]:
ornekDizi = np.arange(0,24)

In [28]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [29]:
ornekDiziKopyasi = ornekDizi.copy()

In [30]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [32]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [34]:
ornekDiziKopyaSlicing[:] = 800

In [35]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [36]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [37]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [38]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [39]:
benimMatrixDizim = np.array(benimListem)

In [40]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [41]:
benimMatrixDizim[0]

array([10, 20, 30])

In [42]:
benimMatrixDizim[1][2]

40

In [43]:
benimMatrixDizim[1,2]

40

In [66]:
benimMatrixDizim[2:,2:]

array([[60]])

In [69]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [70]:
yeniMatrix = np.array(yeniListe)

In [71]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## operasyonlar

In [77]:
yeniBirDizi = np.random.randint(1,100,20)

In [78]:
yeniBirDizi

array([21,  1, 66, 91, 38, 42, 29, 12, 96, 82, 59, 15, 19, 27, 80, 23, 87,
       16, 76, 73])

In [79]:
yeniBirDizi > 24

array([False, False,  True,  True,  True,  True,  True, False,  True,
        True,  True, False, False,  True,  True, False,  True, False,
        True,  True])

In [80]:
yeniBirDizi

array([21,  1, 66, 91, 38, 42, 29, 12, 96, 82, 59, 15, 19, 27, 80, 23, 87,
       16, 76, 73])

In [81]:
sonucDizisi = yeniBirDizi > 24

In [82]:
sonucDizisi

array([False, False,  True,  True,  True,  True,  True, False,  True,
        True,  True, False, False,  True,  True, False,  True, False,
        True,  True])

In [83]:
yeniBirDizi

array([21,  1, 66, 91, 38, 42, 29, 12, 96, 82, 59, 15, 19, 27, 80, 23, 87,
       16, 76, 73])

In [84]:
yeniBirDizi[sonucDizisi]

array([66, 91, 38, 42, 29, 96, 82, 59, 27, 80, 87, 76, 73])

In [85]:
yeniBirDizi

array([21,  1, 66, 91, 38, 42, 29, 12, 96, 82, 59, 15, 19, 27, 80, 23, 87,
       16, 76, 73])

In [86]:
yeniBirDizi[yeniBirDizi > 24]

array([66, 91, 38, 42, 29, 96, 82, 59, 27, 80, 87, 76, 73])

In [87]:
sonDizi = np.arange(0,24)

In [88]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [89]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [90]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [91]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [92]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [93]:
sonDizi / sonDizi

/Users/atilsamancioglu/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [94]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [95]:
np.max(sonDizi)

23

In [96]:
np.min(sonDizi)

0